### ISSUE TITLE
IStringLocalizer missing?

### ISSUE THREAD

**Issue by morgrowe** [LazZiya/XLocalizer#10]
.NET 5
XLocalizer 1.0.0

I'm really excited about being able to store my resources in a database instead of a .resx file.

I followed [these instructions ](https://docs.ziyad.info/en/XLocalizer/v1.0/setup-db.md) to get the XDbResources and XDbCultures tables in my database with seeded data. That worked.

![Seeded data](https://user-images.githubusercontent.com/4726315/101966365-6618a800-3c0f-11eb-8b59-35edd6358f5b.PNG)

I then wanted to see it pulling the translations from my database, so I went to my _ViewImports.cshtml file and added:

`@addTagHelper *, XLocalizer.TagHelpers`

I then went to my Index.cshtml file and added the following line to the top (I'd usually add it to _ViewImports, but it didn't work):

`@inject IStringLocalizer _localizer`

But it doesn't seem to find IStringLocalizer. I had a quick search in the LaZiya/XLocalizer.TagHelpers for the interface, but couldn't find it. Has it been renamed? I got the instructions from: https://docs.ziyad.info/en/XLocalizer/v1.0/localizing-views.md (right at the bottom).

![Reference error](https://user-images.githubusercontent.com/4726315/101966375-6e70e300-3c0f-11eb-88e9-20d3f500f308.PNG)

The error is:

`The type or namespace name 'IStringLocalizer' could not be found`

I may be doing something completely stupid, but would appreciate your insight.

Thanks as always,
Morgan

**Comment by LazZiya** [comment]
Hi @morgrowe 

If you want to inject `IStringLocalizer` to the views you need to add the namespace:

````cshtml
@using Microsoft.Extensions.Localization
@inject IStringLocalizer _localizer

<h1>@_localizer["Welcome"]</h1>
```` 

btw, `XLocalizer` offers more elegant way to localize views, as you already saw in the [docs](https://docs.ziyad.info/en/XLocalizer/v1.0/localizing-views.md), you can use `XLocalizer.TagHelpers` as below:
````cshtml
<h1 localize-content>Welcome</h1>
````

I hope this will help :)

BR,
Ziya

**Comment by morgrowe** [comment]
I knew I was doing something silly! After adding the using statement, it worked.

I like using `localize-content`, but sometimes I need to add localized strings to other attributes. I can see there's a way of localizing the title attribute (`localize-att-title`), but not sure how I'd do it with a custom `data-` attribute or the `alt` attribute, so I usually go with @_localizer[""] to keep things consistent. 

Thanks Ziya.

Morgan

**Comment by LazZiya** [comment]
Don't worry, all of us does such mistakes :)

Just for clarification, you can localize any attribute by adding `localize-att-` prefix as below:

````cshtml
localize-att-title="..."
localize-att-alt="..."
localize-att-src="..."
localize-att-data-whatever="..."
````

Kind regards,
Ziya

**Comment by morgrowe** [comment]
Oh right, I didn't realise. That's great. Looks like I won't need the IStringLocalizer after all. 

Thanks again,
Morgan
