### ISSUE TITLE
? Only data annotations translation

### ISSUE THREAD

**Issue by hrvojej** [LazZiya/XLocalizer#16]
Hi,
how can I have only data annotations translated? I want to disable culture routing but I'm unable to do it.
Data annotations translation is working perfectly however. 
Also is there way to add custom `AccessDenied `page?

I see entry in

```
  <data name="Access denied" xml:space="preserve">
    <value>Pristup zabranjen</value>
    <comment>Areas/Identity/Pages/Account/AccessDenied.cshtml</comment>
  </data>
```
I've added custom page in 
Areas/Identity/Pages/Account/AccessDenied.cshtml
 but it's not being loaded.

**Comment by LazZiya** [comment]
Hi @hrvojej,

I tried to answer all your question, please let me know if you still need any more details.

> how can I have only data annotations translated

Enabling/disabling translation applies for the whole app, it is not possible to enable it for specific part.

> I want to disable culture routing but I'm unable to do it.

If I understand correctly, you don't want the `{culture}` in the url, isn't it? Actually, Asp.Net Core do ont use route based localization by default, and you can use any of the default [Localization Culture Providers](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization-extensibility?view=aspnetcore-5.0#localization-culture-providers) and everything should work fine. Additionaly, if you have followed the [docs](https://docs.ziyad.info/en/XLocalizer/v1.0/setup-xml.md) you can **skip adding** below route template conventions as well:
- `RouteTemplateModelConventionMvc`
- `RouteTemplateModelConventionRazorPages`

> Also is there way to add custom `AccessDenied` page?

This is not related to `XLocalizer`, but I hope [this post](https://stackoverflow.com/questions/38492160/redirect-to-custom-access-denied-page-for-asp-net-core) will help :)

**Comment by hrvojej** [comment]
Thank you for your answer!
I was following [this ](https://medium.com/swlh/step-by-step-tutorial-to-build-multi-cultural-asp-net-core-web-app-3fac9a960c43)tutorial. It's bit different than your documentation.

**Comment by LazZiya** [comment]
You are welcome, that was for my previous project [LazZiya.ExpressLocalization](https://github.com/LazZiya/ExpressLocalization), it dosen't support online translation or auto resource creating. So, it is better to go with XLocalizer, and here you can find its [tutorial](https://medium.com/swlh/xlocalizer-for-asp-net-core-1185b6b9458c).
