### ISSUE TITLE
AmbiguousActionException when using services.AddMvc().AddXDbLocalizer<TDbContext, TTranslator>()

### ISSUE THREAD

**Issue by morgrowe** [LazZiya/XLocalizer#22]
Hi Ziya,

Hope you're well.

I've successfully added XLocalizer.DB to a RazorPages project, but I'm having issues adding it to an existing Mvc project. Despite changes I've tried to make, I either get the 'AmbiguousActionException' exception or the route localization doesn't work at all. It's a very simple project with only one controller.

![sdfsdfdsffff](https://user-images.githubusercontent.com/4726315/113731057-5a864b00-96f0-11eb-9f51-e1d59b167246.PNG)

Here's the Startup.cs:

```cs
public class Startup
    {
        ...

        public void ConfigureServices(IServiceCollection services)
        {
           ...

            var connection = Configuration.GetConnectionString("WLPDB");
            services.AddDbContext<PreferenceFormDbContext>(options =>
                options.UseSqlServer(connection),
                ServiceLifetime.Transient,
                ServiceLifetime.Transient);

            services.Configure<RequestLocalizationOptions>(ops =>
            {
                var supportedCultures = new[]
                {
                    new CultureInfo("cy"),
                    new CultureInfo("en")
                };

                ops.SupportedCultures = supportedCultures;
                ops.SupportedUICultures = supportedCultures;
                ops.DefaultRequestCulture = new RequestCulture("en");

                ops.RequestCultureProviders.Insert(0, new RouteSegmentRequestCultureProvider(supportedCultures));
            });

            services.AddMvc(
                options => {
                    options.EnableEndpointRouting = false;
                })
                .AddMvcOptions(ops => { ops.Conventions.Insert(0, new RouteTemplateModelConventionMvc()); })
                .AddXDbLocalizer<PreferenceFormDbContext, DummyTranslator>(ops =>
                {
                    ops.AutoAddKeys = false;
                    ops.AutoTranslate = false;
                })
                .AddRazorRuntimeCompilation();
            }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRequestLocalization();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
```

And the `Index` method in the `HomeController` is very straight forward:

```cs
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
```

I've got the exception to go away by removing:

```cs
    ops.RequestCultureProviders.Insert(0, new RouteSegmentRequestCultureProvider(supportedCultures));
```
and

```cs
    .AddMvcOptions(ops => { ops.Conventions.Insert(0, new RouteTemplateModelConventionMvc()); })
```

and updating my `MapRoute` to:

```
    routes.MapRoute(
        name: "default",
        template: "{culture=en}/{controller=Home}/{action=Index}/{id?}");
```

But doing this ignores the culture in the URL--it always returns "en", even if "cy" is in the URL.

Any guidance would be really appreciated. I'm more than likely doing something silly again.

Cheers
Morgan

**Comment by LazZiya** [comment]
Hi @morgrowe , glad to see you again :)

For MVC you need to add `[Route]` attribute to the actions:

````cs
public class HomeController : Controller
{
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Route("")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("Privacy")]
        public IActionResult Privacy()
        {
            return View();
        }
}
````
[MVC Sample](https://github.com/LazZiya/XLocalizer.Samples/blob/b35bf19d29a0d37e297d288948567d0f547cbd04/MvcLocalizationSample/MvcLocalizationSample/Controllers/HomeController.cs#L14-L33)

**Comment by morgrowe** [comment]
Hi Ziya

Thank you, as always, for your quick response. Adding the Route decorators fixed that issue. :)

I have one final problem and I can't for the life of me figure out what's doing on.

I have seeded by database with the cultures and some dummy resources:

![res](https://user-images.githubusercontent.com/4726315/113847963-e4d1bc00-978f-11eb-92ed-7ad6b006901b.PNG)

![cul](https://user-images.githubusercontent.com/4726315/113847978-e8654300-978f-11eb-8399-c834e95838b1.PNG)

It doesn't seem to be localizing strings unless the culture is set to my secondary one: `cy`. My default is `en`. So if I go to `/`, or `/en` the culture is correctly being set to `en` but the string isn't being localized:

![xczxxx](https://user-images.githubusercontent.com/4726315/113849888-ce2c6480-9791-11eb-8524-7319d48c42c3.PNG)

However, if I go to `/cy`, it does get localized:

![tesjfjsdfd](https://user-images.githubusercontent.com/4726315/113849714-accb7880-9791-11eb-813c-6f79508e9360.PNG)

Any idea what's going on there? I bet I've misconfigured something in my `Startup.cs`. I haven't changed it since my original post.

Cheers
Morgan

**Comment by LazZiya** [comment]
Hi @morgrowe 

Actually this is already reported in a previous issue #19, I can't say it is a bug, but a design issue that needs enhancement. 

I didn't publish an update yet, but it seems time is already came to fix this :)

**Comment by morgrowe** [comment]
I see! That makes sense. I agree it's not a bug, but it would be great to add the option mentioned in #19 to support key codes. I look forward to the update. :)

Thanks
Morgan

**Comment by LazZiya** [comment]
Hi @morgrowe ,

[Fix is available now.](https://github.com/LazZiya/XLocalizer/issues/19#issuecomment-820524588)

BR,
Ziya

**Comment by LazZiya** [comment]
And for DB version update to [XLocalizer.DB v1.0.2](https://www.nuget.org/packages/XLocalizer.DB/1.0.2)

**Comment by morgrowe** [comment]
Brilliant, thanks Ziya :)
