### ISSUE TITLE
Is it possible to localize <select asp-items />?

### ISSUE THREAD

**Issue by morgrowe** [LazZiya/XLocalizer#27]
Hi Ziya,

Hope you're well.

Is it possible to localize the contents of a `<select asp-items />` automatically?

For example, in a View:
```cshtml
@{
    var items = new List<SelectListItem>();
    items.Add(new SelectListItem
    {
        Text = "Some string to be localized", 
        Value = "SomeValue" 
    });
}
...
<select asp-items="@items"></select>
...
```

I'm not sure where I'd put the `localize-content` or `localize-att-*` to tell it to do its magic.

I haven't tried it, but as a work around, I imagine I could omit the `asp-items` and do it something like this:
```cshtml
<select asp-items="@items">
    @foreach (var item in items)
    {
        <option value="@item.Value" localize-content>@item.Text</option>
    }
</select>
```
But I thought I'd ask in case this is isn't required. :)

Thanks, as always.
Morgan

**Comment by morgrowe** [comment]
Hi Ziya,

Sorry to hear you're not well. I hope you get well soon.

No problem at all--don't even think about it. I'm more than happy to use the workaround :)

Morgan

**Comment by LazZiya** [comment]
Hi @morgrowe ,

Thank you for your kindness, finally I have recovered and feeling better now :)

Your workaround is correct, but this issue inspired me to create a new tag helper...

- Install the latest version of [`XLocalizer.TagHelpers`](https://github.com/LazZiya/XLocalizer.TagHelpers) _currently v1.1.0_
````
Install-Package XLocalizer.TagHelpers -Version 1.1.0
````
- Use `localize-select` to create a select control with all items texts localized:
````html
<localize-select asp-items="@items"></localize-select>
````
This will produce a select list with all option texts localized.

Best regards,
Ziya

**Comment by morgrowe** [comment]
Hi Ziya,

Glad to hear you're feeling better. :)

Ok great, that enhancement will be extremely useful. Thank you!

Morgan
