### ISSUE TITLE
localize-att- in Hyperlinks has forced localize-content

### ISSUE THREAD

**Issue by Sayed-Mahmoud** [LazZiya/XLocalizer#30]
`    <nav class="justify-content-center pagenationNav" aria-label="Page navigation">
        <ul class="pagination">
            <li class="page-item pagenationFirstLI">
                <a asp-route-pageIndex="1" asp-route-sortOrder="@Model.CurrentSort" asp-route-searchString="@Model.CurrentFilter" asp-route-pageSize="@Model.PageSize" aria-label="First" 
localize-att-title="First" 
class="page-link pagenationFirst @prevDisabled">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        </ul>
    </nav>`

**localize-att-title="First"**
warning message: **Resource not exist! Culture: 'ar', Key: '< span aria-hidden="true">&laquo;< /span>'**

**Comment by LazZiya** [comment]
Disable localizing content by setting `localize-content="false"`

````html
<a localize-att-title="First" localize-content="false">
    <span aria-hidden="true">&laquo;</span>
</a>
````
