### ISSUE TITLE
localize-att-* also localize tag's content

### ISSUE THREAD

**Issue by morgrowe** [LazZiya/XLocalizer#33]
Hi Ziya

Hope you're well.

Whenever I use the `localize-att-` tag helper, not only does it localize the attribute's value, but the tag's contents as well. For example:

```cshtml
<p localize-att-title="foo">bar</p>
```

Returns this in the console:

```log
warn: XLocalizer.DB.EF.EFDbResourceProvider[0]
      Resource not exist! Culture: 'cy', Key: 'foo'
warn: XLocalizer.DB.EF.EFDbResourceProvider[0]
      Resource not exist! Culture: 'cy', Key: 'bar'
```

I'd expect it to log:

```log
warn: XLocalizer.DB.EF.EFDbResourceProvider[0]
      Resource not exist! Culture: 'cy', Key: 'foo'
```

I'm using the `localize-att-*` extensively in my project and I'd like to reduce the amount of redundant database traffic. A real world example would be localizing Bootstrap's "close" label. I only want to localize the `aria-label` attribute, not the content of the tag (as it's just an icon).

```cshtml
<button type="button" class="close" data-dismiss="modal" localize-att-aria-label="Close">
    <span aria-hidden="true">&times;</span>
</button>
```

I expect only one request to fetch the resource with the key "Close", but instead I get two. One for "Close" and another for "`<span aria-hidden="true">&times;</span>`".

Is this working as intended? If so, would it be possible to add an option to only localize the tag's contents when `localize-content` is added to the tag please?

Package versions:
```xml
<PackageReference Include="XLocalizer" Version="1.0.3" />
<PackageReference Include="XLocalizer.DB" Version="1.0.3" />
<PackageReference Include="XLocalizer.TagHelpers" Version="1.1.0" />
```

Cheers
Morgan

**Comment by LazZiya** [comment]
Hi @morgrowe ,

Nice to see you again :)

Just use `localize-content="false"`:

````html
<p localize-att-title="foo" localize-content="false">bar</p>
````

**Comment by morgrowe** [comment]
Thanks for the incredibly fast response :). Awesome, `localize-content="false"` works perfectly. Thank you!

Would it be possible to have this as the default behaviour? I can see why some people would like to have the implicit `local-content` behaviour when using the `localize-att-` tag helper, but I think it would be extremely handy if this behaviour could be disabled.

Cheers
Morgan

**Comment by LazZiya** [comment]
you are welcome :) 

I will take your comment into consideration during the next update.

Best,
Ziya

**Comment by morgrowe** [comment]
Great, thank you. :)

Morgan
