### ISSUE TITLE
issue installing package on core 3.1

### ISSUE THREAD

**Issue by ScubaAddict1** [LazZiya/XLocalizer#4]
HI I ran the command bellow and get the following error.
Install-Package XLocalizer

Install-Package : Unable to find package 'XLocalizer'
At line:1 char:1
+ Install-Package XLocalizer
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by ScubaAddict1** [comment]
need to use this command
Install-Package XLocalizer -Version 1.0.0-preview3

**Comment by LazZiya** [comment]
Hi @ScubaAddict1 ,

The package still in preview mode, so adding `-Pre` to the command line will install the latest pre-release:

````
Install-Package XLocalizer -Pre
````

or just like you did to install a specific version.
