### ISSUE TITLE
translating html tags

### ISSUE THREAD

**Issue by Wyciokazz** [LazZiya/XLocalizer#41]
When creating scripts, it will translate this line **<i class="dripicons-document-new" alt="Create"></i>**, how can i disabling?

**Comment by LazZiya** [comment]
Can you show a sample code?

Anyhow, you can disable translation for inner html content using `localize-content="false"`

````html
<!-- assuming you have a select box, and you want to translate its title bot not the inner html -->
<select localize-att-title="Tooltip" localize-content="false">
    <option localize-content>AAA</option>
</select>
````
