### ISSUE TITLE
Translation file for default language?

### ISSUE THREAD

**Issue by xVinCe** [LazZiya/XLocalizer#46]
Hi,

Thank you for this extension, it really helps :)

As the content in the default language is used as a key for the other languages, every time I need to change a text in the default language, I need to change the key in all other languages files.

I would like to do something like:
`<span localize-content>myTranslationCode</span>`

And translate it in all languages including the default.
en is my default language, and I use xml resource files.
I have tried adding a LocSource.en.xml file and a LocSource.xml file but it doesn't work.

So my question is:
Is it possible to have a translation file for the default language? And if so how?

**Comment by LazZiya** [comment]
Glad to know it helps.

To translate the default culture just add this option in startup settings for XLocalizer:

```c#
services.AddRazorPages()
    .AddXLocalizer<LocSource, GoogleTranslateService>(ops =>
    {
        ops.LocalizeDefaultCulture = true;
       //...
    });

```

**Comment by xVinCe** [comment]
It works, thank you!
It would help to have a page in the doc listing all the available options :)
