### ISSUE TITLE
Failed to find out ResourcesPath when hosted in linux

### ISSUE THREAD

**Issue by andreykrivoshapov** [LazZiya/XLocalizer#9]
Thanks for the great job. 

Just found small issue: the ResourcesPath folder is not found when app is hosted in linux docker container. It creates new files with name like ".\LocalizationResources\LocSource.ru.xml" every time and ignore files that exists in "LocalizationResources" folder.

The problem is on this line: https://github.com/LazZiya/XLocalizer/blob/master/XLocalizer/Xml/XmlResourceProvider.cs#L41

It works only on windows now.

![image](https://user-images.githubusercontent.com/22655201/101632875-88f06400-3a37-11eb-8943-7de65edfa396.png)

**Comment by LazZiya** [comment]
Hi @andreykrivoshapov , 

Thank you too for opening this issue, I will try to reproduce and fix it, it may take some time due to year end and being busy with formal business.

Meanwhile, any contributions to solve it earlier are welcome :)

**Comment by andreykrivoshapov** [comment]
Not sure that I prepared Pull Request right :). But it is here: https://github.com/LazZiya/XLocalizer/pull/12

**Comment by LazZiya** [comment]
Thank you @andreykrivoshapov, I will review the PR asap 👍🏼
